---
- name: Install Apache web server
  hosts: dbservers
  become: true

  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: latest

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: true